{
  "dtClaim": "0Zk7h000000GneVCAS",
  "dtBenefits": "aCZWE000002G2Sv4AK",
  "name": "",
  "benefitPayeeRecordId": "aCaWE0000002mbd0AA",
  "dtRelationship": "",
  "dtPayeeCode": "",
  "dtBenefitPercentage": "",
  "dtFromDate": "",
  "dtThroughDate": "",
  "dtPayeeStatus": "",
  "dtPayeeName": "",
  "dtWeeklyAmount": "",
  "dtAddress1": "",
  "dtAddress2": "",
  "dtCity": "",
  "dtState": "",
  "dtZip": "",
  "dtCountry": "",
  "dtFrequency": "",
  "dtClaimPayee": "",
  "dtAwardPerPayee": "",
  "dtEnrollForAutomaticPayment": "",
  "dtElectronicPayment": "",
  "dtNotEligibleForElectronicPayments": ""
}