{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "417",
    "sec-ch-ua": "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"",
    "client_id": "0oadu1v29xL5bCk9W697",
    "x-correlation-id": "",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "content-type": "application/json",
    "client_secret": "8jQuhinEtypykiljFsZbRICMoqE352GW5oSUGJvsbVM7NcpbL9qaB1rl7uwUTMJ2",
    "sec-ch-ua-platform": "\"Windows\"",
    "accept": "*/*",
    "origin": "http://localhost:8081",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/covNonCovMedProviders",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/covNonCovMedProviders",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/covNonCovMedProviders",
  "uriParams": {},
  "rawRequestUri": "/api/covNonCovMedProviders",
  "rawRequestPath": "/api/covNonCovMedProviders",
  "remoteAddress": "/127.0.0.1:54645",
  "requestPath": "/api/covNonCovMedProviders"
}