sfdc:
  password: "![CMMay4LTFCl/8WrngtqxEe+RspHKJCh1/tvg5ALS8jM=]"
  consumerkey: "![iTbq4RULjhxH8wf+n12f2tckmlUfbWpMqqBU74VAogEmq9Oa8n/YXkHfvb7iLTOH88TUf0/rPEtioBCRqeMbVj9QI5qcid91GHNkxNg0HK8XxIWLF4diboUgb7g8XdpH]"
  consumersecret: "![YUL2/SCz7GWuxxM4shR2jxE/dJk6XKkcrmDQ3NZcbSN+IOeOHUXtHi8ApvJ8Fm1CIG7vLBhrYNI1Nd3rox3qAdZTOPaEVg9OMng++OI92f0=]"

# IDP Secure Credentials (replace with your encrypted values)
# These are used for OAuth2 authentication with Anypoint Platform
idp:
  clientId: "![kTR6DgmPkumsaRXHqNOBnSd0QC+BYvDTnA12Z0q481MRxYA/sDWSEcJycmuL3ndX]"
  clientSecret: "![tcOa1QNyqpPS3vFUayXY7WKvn9WiPBa3QMigyyd3Yz7psg4L7Q4ddmaP9DGgGqV1]"
