{
  "claim-object": {
    "sfRecordId": "ASDdfcvg345901CVBUA",
    "Name": null,
    "Claim_Status__c": "K",
    "ReportDate": "2024-02-28",
    "PolicyNumberId": 100998,
    "DT_Actual_Return_to_Work_Date__c": "2024-02-28",
    "DT_Claim_Completed_By__c": "Joe",
    "DT_Claim_Completed_By_Last_Name__c": "Johnson",
    "DT_Claim_Completed_By_phone__c": "111-222-3333",
    "DT_Claim_Completed_By_email__c": "test@lwcc.com",
    "DT_Initial_Actual_RTW__c": "2024-02-28",
    "DT_Initial_Released_to_RTW__c": "2024-02-28",
    "ClaimType": "Medical Only",
    "DT_Injury_Type__c": "04",
    "DT_Employee_discharged_from_medical_care__c": "Y",
    "DT_Date_the_employee_returned_to_work__c": "2024-02-28",
    "DT_Aware_of_a_lawsuit_being_filed__c": "Y",
    "DT_Questionable_claim__c": "N",
    "DT_RPO_Acknowledgement__c": "Y",
    "DT_Claim_involves_the_following__c": "Death claim; Brain injury or head injury with loss of consciousness; ",
    "DT_Intial_Treatment__c": "YYNYNY",
    "Date_of_Accident__c": "2024-02-28",
    "DT_Accident_Time__c": "10:00 AM",
    "DT_Hospitalization__c": "Y",
    "DT_No_Medical_Treatment__c": "N",
    "DT_Minor_treatment_employer__c": "Y",
    "DT_Minor_treatment_clinic__c": "Y",
    "DT_Emergency_Care__c": "N",
    "DT_Lost_Time__c": "Y",
    "DT_Accident_Description__c": "free",
    "DT_Cause_of_Accident_Code__c": "03",
    "DT_Nature_of_Accident_Code__c": "04",
    "DT_What_was_employee_doing__c": "free",
    "DT_Country__c": "US",
    "DT_Point_of_Contact_Name__c": "JACK",
    "DT_Point_of_Contact_Last_Name__c": "JOHNSON",
    "DT_Point_of_Contact_Phone__c": "22233334444",
    "DT_Point_of_Contact_Email__c": "test@lwcc.com",
    "DT_Where_did_accident_happen__c": "R",
    "DT_Denial_Reason_Type__c": "3",
    "DT_Denial_Reason_Detail__c": "D",
    "DT_Date_of_death__c": "2024-02-28",
    "DT_Late_Reporting_Reason__c": "L3",
    "DT_Parish__c": "38",
    "DT_Accident_Zip__c": 70808,
    "DT_Accident_State__c": "GA",
    "DT_Jurisdiction_State__c": "LA",
    "DT_Primary_Accident_Location__c": "Free",
    "DT_Federal_Act__c": "C",
    "DT_Location__c": "F",
    "DT_Loss_of_time_beyond acc__c": "Y",
    "DT_Date_first_lost_time__c": "2024-02-28",
    "DT_Date_first_lost_hour__c": "1:00 PM",
    "DT_Stop_work_immediately__c": "N",
    "DT_Date_returned_to_work__c": "2024-02-28",
    "DT_returned_to_work_hour__c": "4:00 PM",
    "DT_Emp_doing_usual_work__c": "Y",
    "DT_Last_day_paid__c": "2024-02-28",
    "DT_Last_paid_hour__c": "9:00 PM",
    "DT_Days_usually_worked__c": "NYYYYYN",
    "DT_How_Emp_learn_accident__c": "Reported by Supervisor",
    "DT_Med_attention_authorized__c": "Y",
    "DT_Authorization_date__c": "2024-02-28",
    "DT_First_physician_chosen_by_emp__c": "Y",
    "DT_Jurisdiction_Claim_Number__c": "Free",
    "DT_Date_over_60_days_from_injury__c": "N",
    "DT_Date_disabled__c": "2024-02-28",
    "DT_Employee_Missed_More_Than_7_Days__c": "Y",
    "DT_Restricted_Claim__c": "Y",
    "DT_Questionable_claim_explanation": "Freet",
    "DT_Pay_No_Bill__c": "Y",
    "DT_Class_Code__c": "1234566",
    "DT_Risk_Location__c": "520374"
  },
  "injured-worker": [
    {
      "LastName": "JOHNSON",
      "MiddleName": "",
      "FirstName": "JOHN",
      "vlocity_ins__SocialSecurityNumber__c": "999-99-9999",
      "MailingStreet": "123 ELM ST",
      "MailingCity": "BATON ROUGE",
      "MailingState": "LA",
      "MailingPostalCode": "70808",
      "Birthdate": "2024-02-28",
      "DT_Deceased_Date__c": "2024-02-28",
      "Phone": "222-333-4444",
      "FinServ__Gender__c": "M",
      "MailingCountry": "US",
      "DT_Race__c": "04",
      "DT_County__c": "03",
      "OtherPhone": "22233334444",
      "FinServ__PrimaryLanguage__c": "Spanish",
      "DT_Height_ft__c": 6,
      "DT_Height_Inch__c": 2,
      "DT_Weight_lbs__c": 190,
      "DT_Hair_Color__c": "brown",
      "DT_Eye_Color__c": "black",
      "vlocity_ins__DriversLicenseNumber__c": "123",
      "DT_Hobbies__c": "fret",
      "DT_Education_Code__c": "3",
      "Email": "abc@lwcc.com"
    }
  ],
  "claim-participant": [
    {
      "DT_Occupation__c": "6130",
      "DT_Date_Disabled__c": "2024-02-28",
      "DT_Marital_Status__c": "3",
      "DT_Dependent_Children__c": "2",
      "DT_Salary_Continued__c": "Y",
      "DT_Last_Date _Worked__c": "2024-02-28",
      "DT_Days_Worked_Per_Week__c": "5",
      "DT_Full_pay_on_injury_date__c": "Y",
      "DT_Date_employer_notified__c": "2024-02-28",
      "DT_Date_hired__c": "2024-02-28",
      "DT_Wage_rate__c": 150.55,
      "DT_Employee_status_code__c": "12",
      "DT_At_same_wage__c": "Y",
      "DT_Vehicle_Description__c": "free",
      "DT_Dependent_Child_Description__c": "free",
      "DT_Physical_restriction__c": "Y"
    }
  ],
  "injury-details": [
    {
      "DT_How_did_injury_occur__c": "A hammer dropped on knee",
      "DT_Side__c": "L",
      "DT_Finger_toe_injury_location__c": "3",
      "DT_Body_Part__c": "11"
    }
  ]
}