{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "sec-ch-ua": "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"",
    "client_id": "1a3rfe496jfkms49402srr93",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "client_secret": "7o9der492wklsmnxcvrt48f1",
    "sec-ch-ua-platform": "\"Windows\"",
    "accept": "*/*",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en-US,en;q=0.9"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/healthcheck",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/healthcheck",
  "listenerPath": "/api/*",
  "relativePath": "/api/healthcheck",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/healthcheck",
  "rawRequestPath": "/api/healthcheck",
  "remoteAddress": "/127.0.0.1:63304",
  "requestPath": "/api/healthcheck"
}