{
  "claimNumber": 1234,
  "rsTaken": "Yes",
  "resultComments": "Free form text",
  "othrHltPrbl": "Free form text",
  "totalIwisScore": "123",
  "iwis1": "0",
  "iwis2": "1",
  "iwis3": "0",
  "iwis4": "Yes",
  "resultCode": "Contact Successful",
  "treatmentPlan": "Free form text",
  "nextOfficeVisit": "2024-07-15",
  "condition": "Free form text",
  "rtwIndication": "2024-06-16",
  "physician": "Free form text",
  "specialtyCode": "02",
  "contactName": "Free form text",
  "physicianPhone": "111-222-3333",
  "contactPhone": "111-222-3333",
  "contactTextFlag": "true",
  "phEmailAddr": "test@lwcc.com",
  "contactPosition": "Free form text",
  "jobTitle": "Free form text",
  "employType": "F",
  "payType": "CASH",
  "methodOfPayCode": "3",
  "wageRate": 123.45,
  "rtwInd": "No",
  "returnWorkDate": "2024-08-11",
  "witnessInd": "No",
  "rptTo": "Free form text",
  "suprFlg": "Yes",
  "suprNmPhn": "Peter Black 111-222-3333",
  "supEmailAddr": "sup@lwcc.com",
  "vrfyAcdnFct": "Free form text",
  "jobSiteLoc": "Free form text",
  "onJobSite": 212,
  "jobDty": "Free form text",
  "regJobDty": "Free form text",
  "regJobDtyFlg": "Yes",
  "tplInd": "Yes",
  "tplReason": "Free form text",
  "drugPlcy": "Yes",
  "workActionExpl": "Free form text",
  "transDutyInd": "No",
  "sifOnFileInd": "Yes",
  "priorConditionInd": "Yes",
  "priorConditions": "Free form text",
  "choiceInd": "Yes",
  "c1RecvDate": "2024-05-12",
  "lastWorkdate": "2024-01-05",
  "disableDate": "2024-01-15",
  "drugTestingCode": "P",
  "dateHired": "2022-12-18",
  "positionRemaining": "Yes",
  "comments": "Free form text",
  "claimInvType": "ICF"
}