[
  {
    "id": "aCZWE000002G2Sv4AK",
    "name": "BEN-00007",
    "dtClaim": "0ZkWE00000002Ur0AI",
    "dtBenefitType": "TT",
    "dtPaymentFrequency": "Recurring - Monthly",
    "dtAwwAmount": "200.0",
    "dtCompensationRate": "200.0",
    "dtEffectiveDate": null,
    "createdDate": "2024-09-13T07:28:57.000Z",
    "dtStatus": "2",
    "dtCoverageType": "TT",
    "dtFromDate": "2024-08-14",
    "dtTroughDate": "2025-08-14",
    "dtEndReason": "E",
    "dtCoverageStatus": "Q",
    "dtApprovalDate": "2024-08-22",
    "dtVoided": "Y",
    "dtPayFirstDay": "Y",
    "dtFirstDaysPaidFlag": "Y",
    "dtInitialPaymentFlag": "Y",
    "dtWeeklyRate": null,
    "dtCoveragePeriodDays": "365.0",
    "dtCompRateType": "A",
    "dtRateDifference": "-200.0",
    "dtTotalAdjustmentDue": "0.0",
    "dtOneTimePaymentAmount": "200.0",
    "dtTotalDue": "10428.57",
    "dtTotalAward": "0.0",
    "dtMonthlyEarning": null,
    "dtNumberOfYears": null,
    "dtMonthlySebDue": "866.67",
    "dtDependency": null,
    "dtManualCalculation": "N",
    "dtAwwCalcMethod": null,
    "dtOtherFederalDependentBenefitsPrct": null,
    "dtOtherStateDependentBenefitsPrct": null,
    "dtFederalDependentBenefits": null,
    "dtStateDependentBenefits": null
  }
]