{
  "headers": {
    "host": "localhost:8082",
    "connection": "keep-alive",
    "content-length": "50",
    "sec-ch-ua": "\"Chromium\";v=\"128\", \"Not;A=Brand\";v=\"24\", \"Google Chrome\";v=\"128\"",
    "client_id": "1a3rfe496jfkms49402srr93",
    "x-correlation-id": "",
    "sec-ch-ua-mobile": "?0",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    "content-type": "application/json",
    "client_secret": "7o9der492wklsmnxcvrt48f1",
    "sec-ch-ua-platform": "\"macOS\"",
    "accept": "*/*",
    "origin": "http://localhost:8082",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8082/console/",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en-GB,en-US;q=0.9,en;q=0.8"
  },
  "clientCertificate": null,
  "method": "PUT",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/payeeRecord",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/payeeRecord",
  "listenerPath": "/api/*",
  "relativePath": "/api/payeeRecord",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/payeeRecord",
  "rawRequestPath": "/api/payeeRecord",
  "remoteAddress": "/127.0.0.1:65437",
  "requestPath": "/api/payeeRecord"
}