api: 
    id: "19483154"         # replace with real id once added to api manager        
    clientId: ""
    clientSecret: ""
          # API Configurations        
    name: "${project.name}"
    version: "${api.version}"
  
http: 
    port: "8081"

sfdc:
    alias: "mule"
    endpoint: "https://test.salesforce.com/services/oauth2/token"
    audience: "https://test.salesforce.com"
    principal: "sfanypointapi@lwcc.com.sfqauat"  #SFQAUAT
    
claims:
  method: "method"
  basepath: "/api"
  path: "/covNonCovBodyParts"
  port: "443"
  host: "lwcc-claims-prc-api-qa-gqsz9p.internal-vhj0p8.usa-e1.cloudhub.io"
  
mq:
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1/organizations/18404cbf-4922-41d8-a8bd-e903f45d1b04/environments/ec52f0ff-7218-4199-9ddb-76b026bdb5ec"