sfdc:
  password: "![CMMay4LTFCl/8WrngtqxETFYQK6rhDCgMKArlxK2QZ8=]"
  consumerkey: "![iTbq4RULjhxH8wf+n12f2tckmlUfbWpMqqBU74VAogGYdfpwp6ASagAugfd6zUg777rMDxLdTTq2JaQJD3UdlzcJH3mZFW5fQoTdmpi5TLXkecgC7He3DXH4W+rNq2A4]"
  
httpReq:
    claims:
        clientId: "![JDsqIoAl09N8GxClzmCO4RrTsJvwxx2AH2zeklsdUqU=]"
        clientSecret: "![cxe5r5P1hQPLdHmHX9QkXnQT5fB5mn1BSe9CBLZ8UKOTrc+40TmG7jpBrLo/aPkAfVremrHkOfm9GW4SsBHdZqGmJgwAe+8Nm3NfvVIsyqY=]"
    integ:
        clientId: "![JDsqIoAl09N8GxClzmCO4RrTsJvwxx2AH2zeklsdUqU=]"
        clientSecret: "![cxe5r5P1hQPLdHmHX9QkXnQT5fB5mn1BSe9CBLZ8UKOTrc+40TmG7jpBrLo/aPkAfVremrHkOfm9GW4SsBHdZqGmJgwAe+8Nm3NfvVIsyqY=]"

mq:
  client_id: "![KIOQbWIdCYpobTipDbVG+8Qc869azMZuamoxQHune7seUSJHnucjw2/9BM71dXYK]"       #new
  client_secret: "![fHKrxC3gDB9IZry1ZcXabtDruXby0zjd6g8RwUvaeR/QFyggvfCyzQwrYi3CLTUv]"    #new