sfdc:
  password: "![VepmaPkmIKx5fp0dbd6Tey060e4cK6aFccsujPVNUFw=]"
  consumerkey: "![2mmV7ipsbIDbzp8ASZlsVf7IuY3YGeGWz8sIpDD+DZDGuoKcpDpvBhRNC+bDjIUe2qhilc5LDDXddOFLAReUhmsEVdHCFfXqFr3AQb0DCaq2upZtlJAEoSxmVaQ4Q3P3]"  
  
httpReq:
    claims:
        clientId: "![13VLOsawuoODACqM7j6SsG0nwbtM0JanOTk/R0VmYuI=]"
        clientSecret: "![GNgFUyywNtwncdumNUL09w6xKzCif0O9SqMuxBAgWfHuzo9vSt+PrOtdXa+ZsSiYYGZWdeEduYiXYFlmHozPIXRf70ovbLqQY+3cDbTdO7M=]"
    integ:
        clientId: "![13VLOsawuoODACqM7j6SsG0nwbtM0JanOTk/R0VmYuI=]"
        clientSecret: "![GNgFUyywNtwncdumNUL09w6xKzCif0O9SqMuxBAgWfHuzo9vSt+PrOtdXa+ZsSiYYGZWdeEduYiXYFlmHozPIXRf70ovbLqQY+3cDbTdO7M=]"

mq:
  client_id: "![pLA+11j1ANHQMHP4Wl6JJcGZQrGcaZA2gRoOjvNIe52TBIcgAoSDYoYEAX24+gb4]"    #2
  client_secret: "![78nQ1+vQxdQvP825eYLTOzW+VeexTqUDU7er/IoPHJwP2145iZPx2+0hl2MJQWo0]"    #2 