{
  "headers": {
    "client_id": "0oadu1v29xL5bCk9W697",
    "client_secret": "8jQuhinEtypykiljFsZbRICMoqE352GW5oSUGJvsbVM7NcpbL9qaB1rl7uwUTMJ2",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.42.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "6ae46e9c-04ce-4f5c-9154-3647f2b98536",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "37"
  },
  "clientCertificate": null,
  "method": "PATCH",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/claimPayee",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/claimPayee",
  "listenerPath": "/api/*",
  "relativePath": "/api/claimPayee",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/claimPayee",
  "rawRequestPath": "/api/claimPayee",
  "remoteAddress": "/127.0.0.1:54017",
  "requestPath": "/api/claimPayee"
}