{
  "injured-worker": {
            "LastName": "JOHNSON",
            "MiddleName": "",
            "FirstName": "JOHN",
            "vlocity_ins__SocialSecurityNumber__c": "999-99-9999",
            "MailingStreet": "123 ELM ST",
            "MailingCity": "BATON ROUGE",
            "mailingstatecode": "LA",
            "MailingPostalCode": "70808",
            "Birthdate": "2024-02-28",
            "DT_Deceased_Date__c": "2024-02-28",
            "Phone": "222-333-4444",
            "FinServ__Gender__c": "M",
            "MailingCountry": "US",
            "DT_Race__c": "04",
            "DT_County__c": "03",
            "OtherPhone": "22233334444",
            "FinServ__PrimaryLanguage__c": "Spanish",
            "DT_Height_ft__c": 6,
            "DT_Height_Inch__c": 2,
            "DT_Weight_lbs__c": 190,
            "DT_Hair_Color__c": "brown",
            "DT_Eye_Color__c": "black",
            "vlocity_ins__DriversLicenseNumber__c": "123",
            "DT_Hobbies__c": "fret",
            "DT_Education_Code__c": "3",
            "Email": "abc@lwcc.com"
        },
  "claim-object": {
        "DT_Class_Code_Name__c": "34",
        "Date_of_Accident__c": "2024-06-18",
        "DT_Accident_Time__c": "5:00 AM",
        "DT_Accident_Description__c": "test",
        "type": "Claim",
        "DT_Nature_of_Accident_Code__c": "3",
        "Name": "219328",
        "ClaimType": "Medical Only",
        "DT_Claim_Completed_By_phone__c": "555-555-1234",
        "DT_Questionable_claim__c": "No",
        "DT_Intial_Treatment__c": "Emergency care",
        "Id": "0Zk7h000000GnfnCAC",
        "DT_Employee_discharged_from_medical_care__c": "Yes",
        "DT_Claim_Completed_By__c": "John",
        "DT_Employee_Missed_More_Than_7_Days__c": "No",
        "DT_Injury_Type__c": "06 MEDICAL ONLY",
        "DT_Aware_of_a_lawsuit_being_filed__c": "No",
        "Claim_Status__c": "Draft",
        "DT_Claim_Completed_By_Last_Name__c": "Baker",
        "DT_Date_over_60_days_from_injury__c": "No",
        "DT_Initial_Actual_RTW__c": "2024-06-20",
        "DT_Claim_Completed_By_email__c": "john.baker@salesforce.com",
        "DT_Cause_of_Accident_Code__c": "1",
        "DT_Date_the_employee_returned_to_work__c": "2024-06-20",
        "DT_PolicyNumberId__c": "1234",
        "sfRecordId": "0Zk7h000000GnfnCAC",
        "DT_Hospitalization__c": false,
        "DT_No_Medical_Treatment__c": false,
        "DT_Minor_treatment_employer__c": false,
        "DT_Minor_treatment_clinic__c": false,
        "DT_Emergency_Care__c": false,
        "DT_Lost_Time__c": false,
        "DT_Loss_of_time_beyond_acc__c": false,
        "DT_Stop_work_immediately__c": false,
        "DT_Emp_doing_usual_work__c": false,
        "DT_Med_attention_authorized__c": false,
        "DT_First_physician_chosen_by_emp__c": false,
        "DT_Restricted_Claim__c": false,
        "DT_Pay_No_Bill__c": false,
        "DT_RPO_Acknowledgement__c": false
    }
}