[
  {
    "id": "aCZWE00000264B74AI",
    "name": "BEN-00001",
    "dtClaim": "0Zk7h000000GnfnCAC",
    "dtBenefitType": "TP",
    "dtPaymentFrequency": "One Time -  Adjustment",
    "dtAwwAmount": null,
    "dtCompensationRate": null,
    "dtEffectiveDate": null,
    "createdDate": "2024-08-30T15:03:55.000Z",
    "dtStatus": "1",
    "dtCoverageType": "TP",
    "dtFromDate": "2024-08-01",
    "dtTroughDate": "2024-10-24",
    "dtEndReason": null,
    "dtCoverageStatus": null,
    "dtApprovalDate": null,
    "dtVoided": null,
    "dtPayFirstDay": null,
    "dtFirstDaysPaidFlag": null,
    "dtInitialPaymentFlag": null,
    "dtWeeklyRate": null,
    "dtCoveragePeriodDays": "84.0",
    "dtCompRateType": "F",
    "dtRateDifference": "0.0",
    "dtTotalAdjustmentDue": "0.0",
    "dtOneTimePaymentAmount": null,
    "dtTotalDue": "0.0",
    "dtTotalAward": "0.0",
    "dtMonthlyEarning": null,
    "dtNumberOfYears": null,
    "dtMonthlySebDue": "0.0",
    "dtDependency": null,
    "dtManualCalculation": "N",
    "dtAwwCalcMethod": null,
    "dtOtherFederalDependentBenefitsPrct": null,
    "dtOtherStateDependentBenefitsPrct": null,
    "dtFederalDependentBenefits": null,
    "dtStateDependentBenefits": null,
    "dtPaymentStatus": "Authorize"
  }
]