# JSON Logger Configurations [DO NOT DELETE - Also referenced by core-resources-lib]
json.logger.application:           
    name: "${project.artifactId}"
    version: "${project.version}"

#  Needed when testing in Studio and app is restarted since resources filtering in pom will not update these props.                
project:  
    artifactId: "${project.artifactId}"
    version: "${project.version}"
    name: "${project.name}"

health.verbose.client.id: ""

# Include environment independent properties below        
connector:  
    retries: "3"
    retryIntervel: "5000"
    response:  
        timeout: "120000"

